//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Restaurante.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MTczNzg2MUAzMjMxMmUzMTJlMzMzNWRoRWk4eGJoVG9qRjg5Q0wwSm8wTWZwbVFXNENRb1NONnd6UHFOc" +
            "mZNTFU9")]
        public string ClaveSyncfusion {
            get {
                return ((string)(this["ClaveSyncfusion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234")]
        public string ClaveAPIRest {
            get {
                return ((string)(this["ClaveAPIRest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/apirestaurantev3/restaurante/")]
        public string endpointLocal {
            get {
                return ((string)(this["endpointLocal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=imagenesrestaurante;AccountKey=bAp7JRB" +
            "2ZMPX7oB64aQ9L2XlEVqkKeEdO6+DXDjw8m+8OyNJY/RfX37OgexUGctNHTcq/vmZpYfG+AStu3XBkg=" +
            "=;EndpointSuffix=core.windows.net")]
        public string ClaveAzure {
            get {
                return ((string)(this["ClaveAzure"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imagenesproductos")]
        public string NombreContenedor {
            get {
                return ((string)(this["NombreContenedor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://restauranteapi.eastus.cloudapp.azure.com:8080/apirestaurantev3/restaurante" +
            "/")]
        public string endpointAzure {
            get {
                return ((string)(this["endpointAzure"]));
            }
        }
    }
}
